const ROLES = {
  STUDENT: 'STUDENT',
  TUTOR: 'TUTOR',
  ADMIN: 'ADMIN',
};

const OTP_TYPES = {
  REGISTER: 'REGISTER',
  LOGIN: 'LOGIN',
};

const TUTOR_MODES = {
  ONLINE: 'ONLINE',
  OFFLINE: 'OFFLINE',
  BOTH: 'BOTH',
};

const BOOKING_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

const PAYMENT_STATUS = {
  CREATED: 'CREATED',
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
};

const CANCELLED_BY = {
  STUDENT: 'STUDENT',
  TUTOR: 'TUTOR',
};

const VERIFICATION_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

const ID_TYPES = {
  AADHAAR: 'AADHAAR',
  PAN: 'PAN',
  PASSPORT: 'PASSPORT',
};

const REPORT_STATUS = {
  OPEN: 'OPEN',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED',
};

const DAYS = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
};

const LOG_TARGET_TYPES = {
  USER:         'USER',
  REVIEW:       'REVIEW',
  REPORT:       'REPORT',
  VERIFICATION: 'VERIFICATION',
};

module.exports = {
  ROLES,
  OTP_TYPES,
  TUTOR_MODES,
  BOOKING_STATUS,
  PAYMENT_STATUS,
  CANCELLED_BY,
  VERIFICATION_STATUS,
  ID_TYPES,
  REPORT_STATUS,
  DAYS,
  LOG_TARGET_TYPES,
};
